-- 코드를 입력하세요

SELECT INF.REST_ID, 
       REST_NAME, 
       FOOD_TYPE, 
       FAVORITES, 
       ADDRESS, 
       ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO INF, REST_REVIEW REV
WHERE REV.REST_ID = INF.REST_ID
AND ADDRESS LIKE '서울%'
GROUP BY INF.REST_ID, 
       REST_NAME, 
       FOOD_TYPE, 
       FAVORITES, 
       ADDRESS
ORDER BY SCORE DESC, FAVORITES DESC;
